### ISSUE TITLE
missing model2_training_config.yaml

### ISSUE THREAD

**Issue by LuoKaiGSW** [rohitsingh02/kaggle-feedback-english-language-learning-1st-place-solution#2]
Is it possible that the file 'model2_training_config.yaml' is missing?If so, please kindly attach it when you have time. Thank you.

**Comment by rohitsingh02** [comment]
Its there at path `config/model2_training_config.yaml`

**Comment by LuoKaiGSW** [comment]
> 



> Its there at path `config/model2_training_config.yaml`

Thanks!I didn't see it just now.

**Comment by rohitsingh02** [comment]
https://github.com/rohitsingh02/kaggle-feedback-english-language-learning-1st-place-solution/blob/main/config/model2_training_config.yaml
